server:
  port: 8081
azure:
  activedirectory:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    app-id-uri: ${APP_URI}
    tenant-id: ${TENANT_ID}
logging:
  level:
    org:
      springframework:
        security: DEBUG
